---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: kustomize-test
  name: kustomize-test
  namespace: kustomize-demo
  annotations:
    flux.weave.works/automated: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-test
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: kustomize-test
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
